### ISSUE TITLE
KlipperLCD not compatible with Neptune 3 Max

### ISSUE THREAD

**Issue by cnlackey** [joakimtoe/KlipperLCD#5]
The Neptune 3 Max does not have accel sensors which leads to the following errors:

```
Traceback (most recent call last):

File "/home/pi/KlipperLCD/main.py", line 224, in <module>

x = KlipperLCD()

File "/home/pi/KlipperLCD/main.py", line 26, in __init__

self.printer.init_Webservices()

File "/home/pi/KlipperLCD/printer.py", line 439, in init_Webservices

self.max_accel_to_decel = toolhead['max_accel_to_decel']

KeyError: 'max_accel_to_decel
```

A potential solution would be to set default values:
```
    data = self.getREST('/printer/objects/query?toolhead')['result']['status']
    toolhead = data['toolhead']
    volume = toolhead['axis_maximum']  # [x,y,z,w]
    self.MACHINE_SIZE = "{}x{}x{}".format(
        int(volume[0]),
        int(volume[1]),
        int(volume[2])
    )
    self.X_MAX_POS = int(volume[0])
    self.Y_MAX_POS = int(volume[1])
    self.max_velocity = toolhead.get('max_velocity', 0.0)  # Use a default value if the key is not present
    self.max_accel = toolhead.get('max_accel', 0.0)  # Use a default value if the key is not present
    self.max_accel_to_decel = toolhead.get('max_accel_to_decel', 0.0)  # Use a default value if the key is not present
    self.square_corner_velocity = toolhead.get('square_corner_velocity', 0.0)  # Use a default value if the key is not present
    ```
    
 Idk if this logic is correct or not but thought I'd share the issue

**Comment by cclark99** [comment]
Check my recently opened issue. It might solve your problem

**Comment by cnlackey** [comment]
> Check my recently opened issue. It might solve your problem

I posted the solution to the issue in this post. You just set a default value of 0. Confirmed working fix with another users Neptune 3 Max.

**Comment by cybertza** [comment]
#6 
https://github.com/joakimtoe/KlipperLCD/issues/6#issue-2216036284
